#!/bin/bash

# Do not edit this file directly. It is set by the function col_sw()

# default full is commented (basic prompt)
# Uncomenting & setting the value to full or mid acticates 3 or 2 line prompts.
# This allows temporary session-only use of this env-var.
# So in a shared environment with other opinionated users, you can have the
# default non-offensive 1 line prompt (full is commented) showing
# for everyone.
# When you create a new shell session, you can run:
#
# export SET_FULL_PROMPT="full"
# source ~/.bashrc
#
# or:
# col_set_prompt_style "full|mid"
# type alias: csp1 = full
# type alias: csp2 = mid
# type alias: csp3 = mid
#
# The 3 line prompt becomes active for your session only and other users will not have
# to deal with your asthethic design decisions.
# You can still use colsw  to change theme settings. thes ewill not be seen till
# full is set to ""full" or "mid"

SET_FULL_PROMPT="full"

# Theme vars below are unused when SET_FULL_PROMPT is commented
SET_THEME_VAR="196"
SET_BARCOL="\[\033[1;1;31m\]"
SET_TXTCOL="\[\033[0;95m\]"
SET_PATHCOL_VAR="1"
SET_PATHCOL="\[\033[0;37m\]"

